version: '3'
services:
      ubuntu:
              #image: eniocarboni/docker-ubuntu-systemd:latest
              image: diddledani/snapcraft:core20
              network_mode: host
              privileged: true
              restart: no
              tmpfs:
                - /run
                - /tmp
                - /run/lock
              security_opt:
                - apparmor:unconfined
                - seccomp:unconfined
              devices:
                - /dev/fuse
              volumes:
                - /sys/fs/cgroup:/sys/fs/cgroup:ro
                - /lib/modules:/lib/modules:ro
              environment:
                - SAMPLE_ENVIRONMENT_VARIABLE=1 # Might use, might not. We'll see.

              
