---
- hosts: default
  #connection: local
  become: true
  tasks:
    # - name: proxmox add repos
    #   copy:
    #     dest: /etc/apt/sources.list.d/pve-install-repo.list
    #     content: 'deb [arch=amd64] http://download.proxmox.com/debian/pve bookworm pve-no-subscription'
    # - name: Proxmox get gpg key
    #   get_url: 
    #     url: https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg
    #     dest: /etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg
    #     checksum: sha512:7da6fe34168adc6e479327ba517796d4702fa2f8b4f0a9833f5ea6e6b48f6507a6da403a274fe201595edc86a84463d50383d07f64bdde2e3658108db7d6dc87
    - name: Proxmox deb822 repo
      deb822_repository: 
        name: proxmox
        types: deb
        uris: http://download.proxmox.com/debian/pve
        suites: bookworm
        components: pve-no-subscription
        architectures: amd64
        signed_by: https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg
    - name: Upgrade
      apt:
        update_cache: true
        upgrade: full
    - name: install pve kernel
      apt:
        name: pve-kernel-6.2
        state: present
    - name: Install package
      apt:
        name: git
        state: present