---
- hosts: default
  #connection: local
  become: true
  tasks:
    - name: Proxmox deb822 repo
      deb822_repository: 
        name: proxmox
        types: deb
        uris: http://download.proxmox.com/debian/pve
        suites: bookworm
        components: pve-no-subscription
        architectures: amd64
        signed_by: https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg
    - name: Upgrade
      apt:
        update_cache: true
        upgrade: full
    #- name: install pve kernel
    #  apt:
    #    name: pve-kernel-6.2
    #    state: present
    # - name: Remove currently installed kernel
    #   apt:
    #     name: linux-image-amd64 'linux-image-6.1*' os-prober
    #     state: absent
    # - name: update grub
    #   shell: |
    #     echo $USER \
    #     sudo update-grub
    # - name: Reboot the machine
    #   reboot: 
    - name: Reboot the machine
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0
    - name: Wait for the machine to come back online
      wait_for_connection:
        connect_timeout: 60
        sleep: 5
        delay: 5
        timeout: 300
    - name: Install package
      # apt:
      #   name: proxmox-ve postfix open-iscsi
      #   state: present
      apt:
        name: git
        state: present