---
- hosts: default
  become: yes
  tasks:
    - name: Proxmox get repos
      shell: |
        echo "deb [arch\=amd64] http://download.proxmox.com/debian/pve bookworm pve-no-subscription" > /etc/apt/sources.list.d/pve-install-repo.list \
        wget https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg -O /etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg 
    - name: Update and upgrade
      apt:
        update_cache: true
        upgrade: full
    - name: Install package
      apt:
        name: git
        state: present